### ISSUE TITLE
issue with run js test

### ISSUE THREAD

**Issue by mrtuvn** [duhon/magento-docker#10]
Hi 
I trying to test js follow magento base instructions link 
https://devdocs.magento.com/guides/v2.3/test/js/jasmine.html

But when run grunt spec:backend --file="/path/to/the/test.js"
I got error like image below 

![Screenshot from 2020-02-13 16-36-30](https://user-images.githubusercontent.com/1908873/74421191-3548d480-4e7f-11ea-9009-d674e3f770e0.png)
How to fix that. Problem seem come from phantomjs

**Comment by mrtuvn** [comment]
@duhon do you have experience on such case ?
I wonder how to test backend js

**Comment by duhon** [comment]
I have not reproduced this and I don’t know what exactly is the problem there. Try to do like me.
Add nodejs service to docker-compose.yml
```
nodejs:
    image: digitallyseamless/nodejs-bower-grunt
    hostname: nodejs
    volumes:
      - ${MAGENTO_PATH}/magento2ce:/data:${FILE_SYNC}
    tty: true
#    command: sh -c 'cp Gruntfile.js.sample Gruntfile.js && cp package.json.sample package.json && npm install && bash'
    x-hints:
      - https://devdocs.magento.com/guides/v2.3/test/js/jasmine.html
      - grunt spec
    x-setup:
      - bin/magento setup:static-content:deploy -f
```
then:
```
docker-compose up
docker-compose exec app magento reinstall
docker-compose exec nodejs bash
cp Gruntfile.js.sample Gruntfile.js && cp package.json.sample package.json && npm install
```
and run grunt spec:backend --file="/path/to/the/test.js" inner nodejs container
